version: '3.4'

services:
  proxy:
    ports:
      - "8080:80"

  backend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "56009:80"

  frontend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001:80"

  db:
    environment:
      SA_PASSWORD: "ConferencePlanner1234$$"
      ACCEPT_EULA: "Y"
